rave_reviews/index/routes.py
import os
from flask import (
    Flask, flash, render_template, Blueprint,
    redirect, request, session, url_for)

index = Blueprint('index', __name__)


@index.route("/")
def home():
    """
    HOME FUNCTION WHEN NO USER LOGGED IN
    Renders template for the home page
    """
    # If the user is logged in, redirect them to logged in home/landing page
    if 'user' in session:
        return redirect(url_for("index.logged_in_home"))
    return render_template("index.html")


@index.route("/logged_in_home")
def logged_in_home():
    """
    HOME FUNCTION WHEN USER LOGGED IN
    Renders template for the home page
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    return render_template("logged_in_index.html")


@index.route("/contact")
def contact():
    """
    CONTACT PAGE
    Renders template for the contact page
    """
    return render_template("contact.html", title="PLEASE GET IN TOUCH")

rave_reviews/organisations/routes.py
import os
from flask import (
    Flask, flash, render_template, Blueprint,
    redirect, request, session, url_for)
from rave_reviews import mongo
from bson.objectid import ObjectId

organisations = Blueprint('organisations', __name__)


@organisations.route("/get_organisations")
def get_organisations():
    """
    This function renders the organisations template with all
    organisations in the organisation collection
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    # If the user is not admin, redirect them to home/landing page
    if session.get("user") != 'admin':
        return redirect(url_for("index.logged_in_home"))
    try:
        # Retrieve the list of organizations from the database
        # and sort them by "organisation_name" in ascending order
        organisations = list(
            mongo.db.organisation.find().sort("organisation_name", 1))
        # Render the "organisations.html" template
    except Exception as e:
        flash("An exception occurred while retrieving organisations" +
              str(e))
        return redirect(url_for("index.home"))
    return render_template(
        "organisations.html", title="ORGANISATIONS",
        organisations=organisations)


@organisations.route("/add_organisation", methods=["GET", "POST"])
def add_organisation():
    """
    This function adds an organisation to mongoDB
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    # If the user is not admin, redirect them to home/landing page
    if session.get("user") != 'admin':
        return redirect(url_for("index.logged_in_home"))

    # Get the organisation name from the form data
    if request.method == "POST":
        try:
            organisation = {
                "organisation_name": request.form.get("organisation_name")
            }
            # Insert the organisation into the database
            mongo.db.organisation.insert_one(organisation)
            flash("New Organisation Added")
        except Exception as e:
            flash("An exception occurred while adding organisation" +
                  str(e))
        # Redirect to the page that displays all organisations
        return redirect(url_for("organisations.get_organisations"))
    # Render the add_organisation template
    return render_template("add_organisation.html", title="ADD ORGANISATION")


@organisations.route(
    "/edit_organisation/<organisation_id>", methods=["GET", "POST"])
def edit_organisation(organisation_id):
    """
    This function edits an existing organisation
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    # If the user is not admin, redirect them to home/landing page
    if session.get("user") != 'admin':
        return redirect(url_for("index.logged_in_home"))

    if request.method == "POST":
        try:
            # Get the submitted form data
            submit = {
                "organisation_name": request.form.get("organisation_name")
            }
            # Update the organisation in the database
            mongo.db.organisation.update_one(
                {"_id": ObjectId(organisation_id)}, {"$set": submit})
            org = mongo.db.organisation.find_one(
                {"_id": ObjectId(organisation_id)})
            # Retrieve the updated organisation from the database
            org_name = org['organisation_name']
            flash(f"{org_name} Updated")
        except Exception as e:
            flash("An exception occurred while editing organisation" +
                  str(e))
        # Redirect the user to the organisations list page
        return redirect(url_for("organisations.get_organisations"))

    # Retrieve the organisation to be edited from the database
    organisation = mongo.db.organisation.find_one(
        {"_id": ObjectId(organisation_id)})

    # Render the edit_organisation template
    return render_template("edit_organisation.html", title="EDIT ORGANISATION",
                           organisation=organisation)


@organisations.route("/delete_organisation/<organisation_id>")
def delete_organisation(organisation_id):
    """
    This function deletes an existing organisation
    """
    try:
        # finds the organisation name before deleting it
        organisation = mongo.db.organisation.find_one(
            {"_id": ObjectId(organisation_id)})
        organisation_name = organisation['organisation_name']
        mongo.db.organisation.delete_one({"_id": ObjectId(organisation_id)})
        # f string adds organisation name to the flash message once deleted
        flash(f"{organisation_name} is Gone!")
    except Exception as e:
        flash("An exception occurred while deleting organisation" + str(e))
    return redirect(url_for("organisations.get_organisations"))

rave_reviews/raves/routes.py
import os
from flask import (
    Flask, flash, render_template, Blueprint,
    redirect, request, session, url_for)
from rave_reviews import mongo
from bson.objectid import ObjectId
from flask import request
from flask_paginate import Pagination, get_page_args
from math import ceil
import boto3
from werkzeug.utils import secure_filename

# Specify the folder/directory where files will be uploaded
UPLOAD_FOLDER = "uploads"
# Specify the name of the S3 bucket where files will be stored
BUCKET = "rave-review-bucket"

# Create an S3 client object with the provided AWS credentials
s3 = boto3.client('s3',
                  aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
                  aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])

# Create a raves object as a blueprint
raves = Blueprint('raves', __name__)


@raves.route("/get_raves/", methods=["GET"])
def get_raves():
    """
    This function renders the raves template to display
    all raves and if the amount is greater than 4 a
    pagination is displayed
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    try:
        # Get the 'rave_id' from the request arguments
        rave_id = request.args.get('rave_id')
        # Get the page, per_page, and offset values from the request arguments
        page, per_page, offset = get_page_args(
            page_parameter='page', per_page_parameter='per_page',
            offset_parameter='offset')
        # Set the number of items per page to 4
        per_page = 4
        # Create pagination for the raves by calling the pagination function
        raves, num_pages = create_pagination(page, per_page)
        # Find comments in the MongoDB collection
        comments = list(mongo.db.comments.find(
            {"rave_id": rave_id}).sort("comment_created_by", 1))
        # Render the 'raves.html' template with the provided variables
        return render_template(
            "raves.html", title="RAVE REVIEWS",
            raves=raves, comments=comments, num_pages=num_pages, page=page)
    except Exception as e:
        flash("An exception occurred while retrieving rave reviews" + str(e))
        return redirect(url_for("index.home"))


@raves.route("/get_user_raves/", methods=["GET"])
def get_user_raves():
    """
    This function renders the raves template to display
    only the raves uploaded by the user if the amount is
    greater than 4 a pagination is displayed
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))
    try:
        # Get the 'rave_id' from the request arguments
        rave_id = request.args.get('rave_id')
        # Get the page, per_page, and offset values from the request arguments
        page, per_page, offset = get_page_args(
            page_parameter='page', per_page_parameter='per_page',
            offset_parameter='offset')
        # Call the user in session
        session_user = session.get("user")
        # Check if a user session exists and has a valid value
        if session_user:
            # Perform pagination with user-specific information
            raves, num_pages = create_pagination(
                page, per_page, session_user=session_user)
            title = f"{session_user}'s RAVES"
        else:
            # Perform pagination with all information
            raves, num_pages = create_pagination(
                page, per_page)
            title = "RAVE REVIEWS"
        # Find comments in the MongoDB collection
        comments = list(mongo.db.comments.find(
            {"rave_id": rave_id}).sort("comment_created_by", 1))
        # Render the 'raves.html' template with the provided variables
        return render_template(
            "raves.html", title=title,
            raves=raves, comments=comments,
            num_pages=num_pages, page=page, session_user=session_user)
    except Exception as e:
        flash("An exception occurred while retrieving the rave reviews" +
              str(e))
        return redirect(url_for("index.home"))


@raves.route("/search", methods=["GET", "POST"])
def search():
    """
    This function searches the mongo db index and displays
    only the raves with the search criteria if the amount is
    greater than 4 a pagination is displayed
    """
    # Get the query from the form submission
    query = request.form.get("query")
    # Get the 'rave_id' from the request arguments
    rave_id = request.args.get('rave_id')
    # Get the page, per_page, and offset values from the request arguments
    page, per_page, offset = get_page_args(
        page_parameter='page', per_page_parameter='per_page',
        offset_parameter='offset')
    # Find comments in the MongoDB collection
    try:
        comments = list(mongo.db.comments.find(
            {"rave_id": rave_id}).sort("comment_created_by", 1))
        # Render the 'raves.html' template with the provided variables
    except Exception as e:
        flash("An exception occurred while searching the rave reviews" +
              str(e))
        return redirect(url_for("raves.get_raves"))
    # Create pagination for the raves by calling the pagination function
    raves, num_pages = create_pagination(page, per_page, query)
    return render_template(
        "raves.html", title="RAVES",
        raves=raves, comments=comments, num_pages=num_pages, page=page)


@raves.route("/add_rave", methods=["GET", "POST"])
def add_rave():
    """
    This function adds a rave review to mongoDB
    """
    # If the user is not logged in, redirect them to home/landing page
    if 'user' not in session:
        return redirect(url_for("index.home"))

    if request.method == "POST":
        try:
            # Check if the file type is an allowed image file type
            image_url = upload("rave_image")
            if image_url == "invalid":
                flash("Invalid file format. Please use 'JPG', 'jpeg', 'PNG'")
                return redirect(url_for("raves.add_rave"))

            # Retrieve the value of the "rave_set"
            # field from the submitted form
            rave_set_link = request.form.get("rave_set")
            # Call fucntion to modify youtube link
            modified_link = modify_youtube_link(rave_set_link)
            # Check ifbanger is checked and set value
            banger = "on" if request.form.get("banger") else "off"

            # Create a dictionary to store the rave review data
            rave = {
                "organisation_name": request.form.get("organisation_name"),
                "rave_image": image_url,
                "rave_name": request.form.get("rave_name"),
                "date": request.form.get("date"),
                "venue": request.form.get("venue"),
                "rave_description": request.form.get("rave_description"),
                "rave_set": modified_link,
                "banger": banger,
                "created_by": session["user"]
            }
            # Insert dictionary into mongoDB collection
            mongo.db.raves.insert_one(rave)
            flash("Rave Review Uploaded!")
        except Exception as e:
            flash("An exception occurred while adding the review" + str(e))
        # Redirect the user to the page displaying all raves
        return redirect(url_for("raves.get_raves"))
    # Retrieve the list of organisations from the database and sort them
    organisations = mongo.db.organisation.find().sort(
        "organisation_name", 1)
    # Render the "add_rave.html" template
    return render_template(
        "add_rave.html", title="REVIEW RAVE", organisations=organisations)


# S3 Bucket functions
# Allowed image types for uploads
ALLOWED_EXTENSIONS = {'jpg', 'JPG', 'png', 'PNG', 'jpeg'}


def allowed_file(filename):
    """
    Check if the file extension is allowed based on the ALLOWED_EXTENSIONS set.
    """
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def upload(file_key):
    """
    This function uploads the file to an S3
    bucket and returns the generated image URL.
    """
    # Retrieve the file from the request using the provided file key
    f = request.files[file_key]
    # Check if the file exists and the extension is allowed
    if f and allowed_file(f.filename):
        # Generate a secure filename to avoid any security issues
        file_name = secure_filename(f.filename)
        file_content = f.read()
        # Upload the file content to an S3 bucket
        s3.put_object(
            Bucket=BUCKET, Key=file_name, Body=file_content,
            ContentType=f.content_type)
        # Construct the URL of the uploaded image
        image_url = f"https://{BUCKET}.s3.amazonaws.com/{file_name}"
        # Return the generated image URL or "invalid" if file not valid
        return image_url
    else:
        return "invalid"


def modify_youtube_link(link):
    """
    This function takes a YouTube link and
    returns it edited so it will embed correctly
    """
    if "youtube.com" in link:
        if "embed/" not in link:
            if "watch?v=" in link:
                # If the condition is True, replace "watch?v=" with "embed/"
                link = link.replace("watch?v=", "embed/")
                # Remove "&feature=share" if it exists
                link = link.replace("&feature=share", "")
        # Otherwise, already contains "embed/" or is a valid YouTube link
        # and doesn't need any modification
    elif "youtu.be" in link:
        # If link is youtu.be format it is replaced with
        # the web based embed structure
        link = link.replace(
            "youtu.be/", "www.youtube.com/embed/")
    else:
        # Ignore the link if it is not a YouTube link
        link = ""
    return link


@raves.route("/edit_rave/<rave_id>", methods=["GET", "POST"])
def edit_rave(rave_id):

rave_reviews/templates/add_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="blank-background">
    <h1 class="title">{{ title }}</h1>

    <div class="row">
        <form class="add_rave" method="POST" action="{{ url_for('organisations.add_organisation') }}">
            <div class="row">
                <!-- Organisation name -->
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fa-solid fa-people-group prefix fa-icon"></i>
                        <input id="organisation_name" name="organisation_name" type="text" maxlength="20"
                            class="validate" required>
                        <label for="organisation_name" aria-label="Enter organisation name">Organisation Name</label>
                    </div>
                </div>
                <!-- submit button -->
                <div class="row">
                    <div class="col s12 center-align">
                        <i class="fa-solid fa-arrow-up-from-square"></i>
                        <a href="{{ url_for('organisations.get_organisations' )}}" class="btn">Cancel</a>
                        <button type="submit" value="Upload" class="btn" aria-label="Add organisation">Add Organisation</button>
                    </div>
                </div>
        </form>
    </div>
</div>

{% endblock %}

rave_reviews/templates/contact.html
{% extends "base.html" %}
{% block content %}
<div class="blank-background">

    <h1 class="title">{{ title }}</h1>

    <div class="row">
        <div class="col-12 form-container">
            <form class="contact-form" onsubmit="return sendMail(this);">
                <label for="name" aria-label="Enter name">Name</label><br>
                <input type="text" name="name" id="name" placeholder="Name" required><br>
                <label for="emailaddress" aria-label="Enter email">Email</label><br>
                <input type="email" name="email" id="emailaddress" placeholder="Email" required><br>
                <label for="message" aria-label="Write message">Message</label><br>
                <textarea rows="5" name="message" id="message" placeholder="Please ask us a question..."
                    required></textarea><br>
                <div id="form-btn">
                    <button type="submit" class="btn" aria-label="Submit contact form">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

rave_reviews/templates/edit_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="blank-background">
    <h1 class="title">{{ title }}</h1>

    <div class="row">
        <form class="add_rave" method="POST"
            action="{{ url_for('organisations.edit_organisation', organisation_id=organisation._id) }}">
            <div class="row">
                <!-- Organisation name -->
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fa-solid fa-people-group prefix fa-icon"></i>
                        <input id="organisation_name" name="organisation_name" type="text" maxlength="20"
                            class="validate" value="{{ organisation.organisation_name }}" required>
                        <label for="organisation_name" aria-label="Enter organisation name">Organisation Name</label>
                    </div>
                </div>
                <!-- submit button -->
                <div class="row">
                    <div class="col s12 center-align">
                        <i class="fa-solid fa-arrow-up-from-square"></i>
                        <a href="{{ url_for('organisations.get_organisations' )}}" class="btn" aria-label="Cancel edit">Cancel</a>
                        <button type="submit" value="Upload" class="btn" aria-label="Confirm edit">Edit Organisation</button>
                    </div>
                </div>
        </form>
    </div>
</div>

{% endblock %}

rave_reviews/templates/logged_in_index.html
{% extends "base.html" %}
{% block content %}
<div class="background-image center-align">
    <h1 class="title">{{ title }}</h1>
    <div class="row">
        <img src="{{ url_for('static', filename='images/rr-logo-main.png') }}" class="main-logo"
            alt="Raves Reviews logo">
        <div class="welcome-container">
            <h2 class="title">Rave Reviews</h2>
            <p>This site is designed for Drum and Bass enthusiastics to share their experiences, favourite sets and
                raves.</p>
            <p>Please be friendly, foul behaviour, comments or reviews will result in removal of the site.</p>
            <p><i class="fa-regular fa-hand-peace prefix fa-icon"></i> Peace and Love <i
                    class="fa-regular fa-heart prefix fa-icon"></i></p>
            <a href="{{ url_for('raves.get_user_raves', rave_id=rave_id) }}" aria-label="go to my reviews page" class="btn">My Reviews</a>
            <a href="{{ url_for('raves.add_rave') }}" aria-label="go to leave review page" class="btn">Leave Review</a>
            <a href="{{ url_for('raves.get_raves') }}" aria-label="go to rave review page" class="btn">Rave Reviews</a>
        </div>
    </div>
</div>
{% endblock %}

rave_reviews/templates/organisations.html
{% extends "base.html" %}
{% block content %}

<h1 class="title">{{ title }}</h1>

<div class="row">
    <div class="center-align">
        <a href="{{ url_for('organisations.add_organisation' )}}" class="btn org-btn" aria-label="Add organisation">Add Organisation</a>
    </div>
</div>

<div class="row">
    {% for organisation in organisations %}
    <div class="col s12 m6 l4 xl3">
        <div class="card org-card center-align">
            <div class="card-content white-text">
                <span class="card-title">{{ organisation.organisation_name }}</span>
                <div class="card-action">
                    <a href="{{ url_for('organisations.edit_organisation', organisation_id=organisation._id) }}"
                        class="btn">Edit</a>
                    <button onClick="deleteOrganisationModal('{{ organisation._id }}')" class="btn" aria-label="Delete organisation">Delete</button>
                </div>
            </div>
        </div>
        <!-- Delete Modal -->
        <div class="modal-background" id="modal-background-{{ organisation._id }}">
            <div class="row">
                <div class="center-align organisation-modal" id="organisation-modal-{{ organisation._id }}">
                    <div class="col-12">
                        <header class="modal-header">
                            <h2>
                                Are you sure you want to delete {{ organisation.organisation_name }}!?
                            </h2>
                        </header>
                        <div class="modal-body">
                            <button onClick="closeOrgModal('{{ organisation._id }}')" class="btn" aria-label="Cancel deletion">Cancel</button>
                            <a href="{{ url_for('organisations.delete_organisation',organisation_id=organisation._id) }}"
                                class="btn" aria-label="Confirm delete">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

rave_reviews/templates/raves.html
{% extends "base.html" %}
{% block content %}
<div class="blank-background center-align">
    <h1 class="title">{{ title }}</h1>

    <div class="row">
        <form action="{{ url_for('raves.search', rave_id=rave_id )}}" method="post" class="search-form">
            <div class="row center-align">
                <div class="input-field col s12 m8">
                    <i class="fa-solid fa-magnifying-glass prefix fa-icon"></i>
                    <input type="text" id="query" name="query" minlength="3" class="validate search-input" required>
                    <label for="query">Search Raves</label>
                </div>
                <div class="search-btn">
                    <a href="{{ url_for('raves.get_raves') }}" class="btn">Reset</a>
                    <button type="submit" class="btn">Search</button>
                </div>
            </div>
            <a href="{{ url_for('raves.get_user_raves', rave_id=rave_id) }}" class="btn">My Reviews</a>
        </form>
    </div>
    {% set rave_list = raves|list %}
    {% if rave_list|length > 0 %}
    <div class="card-container center-align">
        {% for rave in rave_list %}
        <div class="card">
            <ul class="collapsible">
                <li>
                    <div class="collapsible-header">
                        <h2 class="rave-title">{{ rave.rave_name }}
                            {% if rave.banger == "on" %}
                            <i class="fa-solid fa-bullhorn fa-icon tooltipped" data-position="right"
                                data-tooltip="PROPER NAUGHTY!"></i>
                            {% endif %}
                        </h2>
                        <i class="fa-solid fa-hand-point-down fa-icon"></i>
                    </div>
                    <div class="collapsible-body center-align">
                        <div class="card-image">
                            <img src="{{ rave.rave_image }}" class="materialboxed">
                        </div>
                        <div class="card-content">
                            <h5>Organisation: {{ rave.organisation_name }}</h5>
                            <p>Rave Date: {{ rave.date }}
                                <P>Venue: {{ rave.venue }}</P>
                                <p>{{ rave.rave_description }}</p>
                                {% if rave.rave_set %}
                                <iframe class="youtube-vid" width="560" height="315" src="{{rave.rave_set}}"
                                    title="YouTube video player" frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                    allowfullscreen></iframe>
                                {% endif %}
                                <p><em>Raver: {{ rave.created_by }}</em></p>
                        </div>
                        <div class="comments" id="comments-{{comment_id}}">
                            {% for comment in comments %}
                            {% if comment.comment_id == rave._id %}
                            <p>{{ comment.comment_created_by}}: {{ comment.comment_text }}</p>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <!-- Add comment form -->
                        <form method="POST" enctype="multipart/form-data"
                            action="{{ url_for('raves.add_comment', rave_id=rave._id) }}" class="validate">

                            <div class="comment-section" id="comment-section-{{comment_id}}">
                                <label for="comment" hidden>Comment</label>
                                <textarea class="comment-box textarea" name="comment" id="comment"></textarea>
                            </div>
                            <button class="btn comment-btn" type="submit">Post comment</button>
                        </form>
                        <div class="card-action">
                            {% if session.user|lower == rave.created_by|lower or session.user|lower == 'admin' %}
                            <a href="{{ url_for('raves.edit_rave', rave_id=rave._id) }}" class="btn" aria-label="Edit review">Edit Review</a>
                            <button onClick="deleteReviewModal('{{ rave._id }}')" class="btn" aria-label="Delete review">Delete Review</button>
                            {% endif %}
                            {% if session.user|lower == 'admin' %}
                            <button onClick="deleteCommentsModal('{{ rave._id }}')" class="btn" aria-label="Delete comments">Delete Comments</button>
                            {% endif %}
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <!-- Delete Review Modal -->
        <div class="modal-background" id="modal-background-{{ rave._id }}">
            <div class="row">
                <div class="center-align review-modal" id="rave-modal-{{ rave._id }}">
                    <div class="col-12">
                        <header class="modal-header">
                            <h2>
                                Are you sure you want to delete your {{rave.rave_name }} review!?
                            </h2>
                        </header>
                        <div class="modal-body">
                            <button onClick="closeRaveModal('{{ rave._id }}')" class="btn">Cancel</button>
                            <a href="{{ url_for('raves.delete_rave', rave_id=rave._id) }}" class="btn">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Delete Comments Modal -->
        <div class="modal-background" id="comments-background-{{ rave._id }}">
            <div class="row">
                <div class="center-align review-modal" id="comments-modal-{{ rave._id }}">
                    <div class="col-12">
                        <header class="modal-header">
                            <h2>
                                Are you sure you want to delete the {{rave.rave_name }} comments!?
                            </h2>
                        </header>
                        <div class="modal-body">
                            <button onClick="closeCommentsModal('{{ rave._id }}')" class="btn">Cancel</button>
                            <a href="{{ url_for('raves.delete_comment', rave_id=rave._id) }}" class="btn">Delete Comments</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h3 class="title">No Review Found!</h3>
    {% endif %}
    <!-- pagination -->
    <div class="pagination-keys">
        {% if page > 1 %}
        <a href="/get_raves/?page={{ page - 1 }}&per_page={{ per_page }}&offset={{ offset }}" class="page-link" aria-label="Go to previous pagination page"><i
                class="fa-solid fa-hand-point-left prefix"></i></a>
        {% endif %}
        {% for p in range(1, num_pages + 1) %}
        {% if p == page %}
        <a href="/get_raves/?page={{ p }}&per_page={{ per_page }}&offset={{ offset }}" class="page-num active" aria-label="Go to page number">{{ p }}</a>
        {% else %}
        <a href="/get_raves/?page={{ p }}&per_page={{ per_page }}&offset={{ offset }}" class="page-num" aria-label="Go to page number">{{ p }}</a>
        {% endif %}
        {% endfor %}
        {% if page < num_pages %}
        <a href="/get_raves/?page={{ page + 1 }}&per_page={{ per_page }}&offset={{ offset }}" class="page-link" aria-label="Go to next pagination page"><i
                class="fa-solid fa-hand-point-right prefix"></i></a>
        {% endif %}
    </div>
</div>
{% endblock %}